
apiVersion: v1
kind: Service
metadata:
  name: serving-model
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
  selector:
    app: serving-model
