schedule: "*/30 * * * *"  # Run every 30 minutes

image:
  repository: ml-platform/training-service
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
