{{- if .Values.servingModel.enabled }}
# Serving Model Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serving-model
  labels:
    {{- include "ml-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.servingModel.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: serving-model
  template:
    metadata:
      labels:
        app: serving-model
    spec:
      containers:
        - name: serving-model
          image: {{ .Values.global.imageRegistry }}/{{ .Values.servingModel.image.repository }}:{{ .Values.servingModel.image.tag }}
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: {{ .Values.global.db.host }}
            - name: DB_NAME
              value: {{ .Values.global.db.name }}
            - name: DB_USER
              value: {{ .Values.global.db.user }}
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.secretName }}
                  key: DB_PASSWORD
---
# Serving Model Service
apiVersion: v1
kind: Service
metadata:
  name: serving-model
  labels:
    {{- include "ml-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.servingModel.service.port }}
      targetPort: 8081
  selector:
    app: serving-model
{{- end }}
