
schedule: "*/5 * * * *"  # Run every 5 minutes

image:
  repository: traffic-sender
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
