schedule: "*/5 * * * *"  # Run every 5 minutes

image:
  repository: ml-platform/traffic-sender
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
