
replicaCount: 2

image:
  repository: serving-model
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
