replicaCount: 1

image:
  repository: 615299766383.dkr.ecr.ap-south-1.amazonaws.com/my-app-serving
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

global:
  db:
    host: "database-2.cluster-ch4kwmsespel.ap-south-1.rds.amazonaws.com"
    name: "first_1"
    user: "postgre"
    secretName: "db-secret"
