apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: {{ .Values.global.db.host }}
            - name: DB_NAME
              value: {{ .Values.global.db.name }}
            - name: DB_USER
              value: {{ .Values.global.db.user }}
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.db.secretName }}
                  key: DB_PASSWORD
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
