apiVersion: batch/v1
kind: CronJob
metadata:
  name: traffic-sender
spec:
  schedule: {{ .Values.trafficSender.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: traffic-sender
              image: {{ .Values.global.imageRegistry }}/{{ .Values.trafficSender.image.repository }}:{{ .Values.trafficSender.image.tag }}
              env:
                - name: DB_HOST
                  value: {{ .Values.global.db.host }}
                - name: DB_NAME
                  value: {{ .Values.global.db.name }}
                - name: DB_USER
                  value: {{ .Values.global.db.user }}
                - name: DB_PORT
                  value: "5432"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.db.secretName }}
                      key: DB_PASSWORD
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: OnFailure
