
apiVersion: batch/v1
kind: CronJob
metadata:
  name: traffic-sender
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: traffic-sender
              image: {{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.db.secretName }}
                      key: DB_PASSWORD
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: OnFailure
